Escuela/Escuela/Controllers/CourseController.cs
using Escuela.Entidades;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class CourseController : Controller
    {
        private ICourse icourses;
        public CourseController(ICourse icourses)
        {
            this.icourses = icourses;
        }
        public IActionResult Index()
        {
            var listado = icourses.ListarCursos().Where(x => x.Estado == 1).Select(x => x).ToList();

            return View(listado);
        }
        public IActionResult Datos(int id)
        {
            if (id != 0)
            {
                Course st = icourses.ListarCursos().Where(x => x.CourseId == id).Select(x => x).FirstOrDefault();
                return View(st);
            }
            else
            {
                return View();
            }

        }
        [HttpPost]
        public IActionResult Guardar(Course cs)
        {
            Course c = new Course();

            if (cs.CourseId != 0)
            {
                c.CourseId = cs.CourseId;
                c.Title = cs.Title;
                c.Credits = cs.Credits;
                c.Estado = 1;
                icourses.Update(c);

                return RedirectToAction("Index");

            }
            else
            {


                c.Title = cs.Title;
                c.Credits = cs.Credits;
                c.Estado = 1;
                icourses.Insertar(c);

                return RedirectToAction("Index");
            }

        }
        public IActionResult Confirmacion(int id)
        {
            /*hice esta vista por que si ocupaba el lamda directamente en delete me daba un error, fue la unica
            solucion que encontre*/
            Course cs = icourses.ListarCursos().Where(x => x.CourseId == id).Select(x => x).FirstOrDefault();
            return View(cs);
        }

        [HttpPost]
        public IActionResult Delete(Course cs)
        {
            Course c = new Course();
            c.CourseId = cs.CourseId;
            c.Title = cs.Title;
            c.Credits = cs.Credits;
            c.Estado = 0;
            icourses.Update(c);
            return Redirect("/Course/Index");
        }
    }
}

Escuela/Escuela/Controllers/EnrrollmentController.cs
using Escuela.Entidades;
using Escuela.Repositorio;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class EnrrollmentController : Controller
    {
        private IRollements irollements;
        private ICourse icourse;
        private IStudent istudent;

        public EnrrollmentController(IRollements irollements, ICourse icourse, IStudent istudent)
        {
            this.irollements = irollements;
            this.icourse = icourse;
            this.istudent = istudent;
        }
        public IActionResult Index()
        {
            var listado = irollements.ListarEnrrollments();
            var arreglo = (from datos in listado
                           where datos.Course.Estado == 1 &&
                           datos.Student.Estado == 1
                           select datos).ToList();
                          
            return View(arreglo);
        }
        public IActionResult Datos()
        {          
                var Grado = Enum.GetValues(typeof(Grade));
                var Cursos = icourse.ListarCursos().Where(x=>x.Estado == 1).Select(x=>x);
                var Estudiantes = istudent.ListarEstudiantes().Where(x=>x.Estado == 1).Select(x=>x);
                List<SelectListItem> ItemGrado = new List<SelectListItem>();
                List<SelectListItem> ItemCurso = new List<SelectListItem>();
                List<SelectListItem> ItemEstudiantes = new List<SelectListItem>();
                foreach (var items in Cursos)
                {
                    ItemCurso.Add(
                        new SelectListItem
                        {
                             Text = items.Title,
                            Value = items.CourseId.ToString(),
                            
                        });
                        ViewBag.Cursos = ItemCurso;
                }
                foreach (var items in Estudiantes)
                {
                    ItemEstudiantes.Add(
                        new SelectListItem
                        {
                            Text = (items.FirstMidName +" "+ items.LastName),
                            Value = items.StudentId.ToString()
                        });
                        ViewBag.Estudiantes = ItemEstudiantes;
                }
                foreach (var items in Grado)
                {
                    ItemGrado.Add(
                        new SelectListItem
                        {
                            Text = Enum.GetName(typeof(Grade),items),
                            Value = ((int)items).ToString()
                        });
                    ViewBag.Grado = ItemGrado;
                }
                return View();
        }
        public IActionResult Guardar(Enrollment Et)
        {
            
             Enrollment e = new Enrollment();
                
                e.StudentID = Et.StudentID;
                e.CourseID = Et.CourseID;
                e.Grade = Et.Grade;
                irollements.Insertar(e);

                return RedirectToAction("Index");
           
        }

        public IActionResult Delete(int id)
        {
            Enrollment en = irollements.ListarEnrrollments().Where(x=>x.EnrollmentId == id).Select(x=>x).FirstOrDefault();
            irollements.Delete(en);
            return RedirectToAction("Index");
        }
    }
}

Escuela/Escuela/Controllers/StudentController.cs
using Escuela.Entidades;
using Escuela.Servicio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class StudentController : Controller
    {
        private IStudent istudent;

        public StudentController(IStudent istudent)
        {
            this.istudent = istudent;
        }
        public IActionResult Index()
        {
            var listado = istudent.ListarEstudiantes().Where(x => x.Estado == 1).Select(x => x).ToList();

            return View(listado);
        }
        public IActionResult Datos(int id)
        {
            if (id != 0) {
                Students st = istudent.ListarEstudiantes().Where(x => x.StudentId == id).Select(x => x).FirstOrDefault();
                return View(st);
            }
            else
            {
                return View();
            }

        }

        [HttpPost]
        public IActionResult Guardar(Students st)
        {
            Students s = new Students();

            if (st.StudentId != 0)
            {
                s.StudentId = st.StudentId;
                s.FirstMidName = st.FirstMidName;
                s.LastName = st.LastName;
                s.EnrollmentsDate = st.EnrollmentsDate;
                s.Estado = 1;
                istudent.Update(s);

                return RedirectToAction("Index");

            }
            else
            {

                s.FirstMidName = st.FirstMidName;
                s.LastName = st.LastName;
                s.EnrollmentsDate = st.EnrollmentsDate;
                s.Estado = 1;
                istudent.Insertar(s);

                return RedirectToAction("Index");
            }

        }
        public IActionResult Confirmacion(int id)
        {
            /*hice esta vista por que si ocupaba el lamda directamente en delete me daba un error, fue la unica
            solucion que encontre*/
            Students st = istudent.ListarEstudiantes().Where(x => x.StudentId == id).Select(x => x).FirstOrDefault();
            return View(st);
        }

        [HttpPost]
        public IActionResult Delete(Students st)
        {
            
            Students s = new Students();
            s.StudentId = st.StudentId;
            s.FirstMidName = st.FirstMidName;
            s.LastName = st.LastName;
            s.EnrollmentsDate = st.EnrollmentsDate;
            s.Estado = 0;
            istudent.Update(s);
            return Redirect("/Student/Index");
        }

    }
}

Escuela/Escuela/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Escuela</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Escuela</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Estudiente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrrollment" asp-action="Index">Matriculación</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Escuela - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>